In [1]:
import numpy as np

# Concatenation in numpy array

In [2]:
array1=np.array([[1,2,3],[4,5,6],[7,8,9]])
array1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
array1=np.array([1,2,3,4])
array2=np.array([5,6,7,8])
array3=np.concatenate((array1,array2))
array3

array([1, 2, 3, 4, 5, 6, 7, 8])

# 2D array concatenation

In [4]:
array1=np.array([[1,2,3,4],
                 [4,5,6,7],
                 [7,8,9,7]])
array2=np.array([[8,2,5,7],
                 [4,7,0,7],
                 [7,9,8,7]])

In [5]:
np.concatenate((array1,array2),axis=0)

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [7, 8, 9, 7],
       [8, 2, 5, 7],
       [4, 7, 0, 7],
       [7, 9, 8, 7]])

In [6]:
np.concatenate((array1,array2),axis=1)

array([[1, 2, 3, 4, 8, 2, 5, 7],
       [4, 5, 6, 7, 4, 7, 0, 7],
       [7, 8, 9, 7, 7, 9, 8, 7]])

# hstack and vstack

In [7]:
array1=np.array([[1,2,3,4],
                 [4,5,6,7]])
array2=np.array([[8,2,5,7]])

In [8]:
np.vstack((array1,array2))

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [8, 2, 5, 7]])

In [9]:
array3=np.array([[23],
                 [34]])


In [10]:
np.hstack((array1,array3))

array([[ 1,  2,  3,  4, 23],
       [ 4,  5,  6,  7, 34]])

# Slicing in numpy array 

In [11]:
array1=np.arange(1,11)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
array=array1[3:7]
array

array([4, 5, 6, 7])

# For 2D array slicing 

In [13]:
array2=np.array([[4,5,6,7],
                 [12,23,45,67],
                 [12,32,45,66]])
array2.shape

(3, 4)

In [14]:
print(array2[1,1])

23


In [15]:
print(array2[1,3])

67


In [16]:
print(array2[2,2])

45


In [17]:
array2[1:3,1:3]

array([[23, 45],
       [32, 45]])

In [18]:
array2[0:,1:3]

array([[ 5,  6],
       [23, 45],
       [32, 45]])

# Reshaping method in numpy array 

In [19]:
array2

array([[ 4,  5,  6,  7],
       [12, 23, 45, 67],
       [12, 32, 45, 66]])

In [20]:
array2.shape

(3, 4)

In [21]:
array2.reshape(4,3)

array([[ 4,  5,  6],
       [ 7, 12, 23],
       [45, 67, 12],
       [32, 45, 66]])

In [22]:
array2.reshape(2,6)

array([[ 4,  5,  6,  7, 12, 23],
       [45, 67, 12, 32, 45, 66]])

In [23]:
array2.reshape(6,2)

array([[ 4,  5],
       [ 6,  7],
       [12, 23],
       [45, 67],
       [12, 32],
       [45, 66]])

In [24]:
array2.reshape(12)

array([ 4,  5,  6,  7, 12, 23, 45, 67, 12, 32, 45, 66])

In [25]:
array2.reshape(2,3,2)

array([[[ 4,  5],
        [ 6,  7],
        [12, 23]],

       [[45, 67],
        [12, 32],
        [45, 66]]])

In [26]:
array=np.arange(1,101)
array

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [27]:
array.reshape(20,5)

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

# Day 4

# Random array in numpy

In [28]:
# rand() gives the random value betwen 0-1
# randint() gives the random integer value in given range

In [29]:
array_1= np.random.rand(4, 6)
array_1

array([[0.95639636, 0.98790302, 0.81132381, 0.1657973 , 0.00161266,
        0.46086836],
       [0.6948953 , 0.36599416, 0.02585246, 0.85693348, 0.618602  ,
        0.18701966],
       [0.4314908 , 0.49673042, 0.4396495 , 0.13618235, 0.44690528,
        0.96093182],
       [0.19872346, 0.57625363, 0.43377108, 0.14425984, 0.27148636,
        0.80037417]])

In [30]:
array_2= np.random.rand(10)
array_2

array([0.5688089 , 0.93063132, 0.85965384, 0.96217424, 0.52542384,
       0.71761377, 0.91349818, 0.39137311, 0.58839872, 0.73198876])

# Randint method

In [31]:
array3= np.random.randint(1,100,size=10)
array3

array([39, 85, 81, 29, 43, 93, 92, 96, 77, 17], dtype=int32)

# splitting in numpy array 

In [32]:
array1=np.random.randint(100,500,size=(10,6))
array1

array([[399, 376, 247, 496, 375, 443],
       [444, 145, 220, 360, 371, 277],
       [222, 142, 490, 382, 387, 314],
       [156, 203, 465, 318, 292, 119],
       [196, 196, 193, 428, 355, 458],
       [150, 259, 196, 467, 490, 363],
       [122, 237, 288, 147, 110, 491],
       [265, 235, 392, 499, 471, 267],
       [247, 267, 278, 162, 314, 153],
       [273, 314, 146, 106, 131, 109]], dtype=int32)

# Split function in numpy array

In [33]:
array1_1,array1_2=np.split(array1,2,axis=0)

In [34]:
array1_1

array([[399, 376, 247, 496, 375, 443],
       [444, 145, 220, 360, 371, 277],
       [222, 142, 490, 382, 387, 314],
       [156, 203, 465, 318, 292, 119],
       [196, 196, 193, 428, 355, 458]], dtype=int32)

In [35]:
array1_2

array([[150, 259, 196, 467, 490, 363],
       [122, 237, 288, 147, 110, 491],
       [265, 235, 392, 499, 471, 267],
       [247, 267, 278, 162, 314, 153],
       [273, 314, 146, 106, 131, 109]], dtype=int32)

In [36]:
array1_1,array1_2=np.split(array1,2,axis=1)

In [37]:
array1_1

array([[399, 376, 247],
       [444, 145, 220],
       [222, 142, 490],
       [156, 203, 465],
       [196, 196, 193],
       [150, 259, 196],
       [122, 237, 288],
       [265, 235, 392],
       [247, 267, 278],
       [273, 314, 146]], dtype=int32)

In [38]:
array1_2

array([[496, 375, 443],
       [360, 371, 277],
       [382, 387, 314],
       [318, 292, 119],
       [428, 355, 458],
       [467, 490, 363],
       [147, 110, 491],
       [499, 471, 267],
       [162, 314, 153],
       [106, 131, 109]], dtype=int32)

In [39]:
array1=np.random.randint(100,500,size=(9,6))
array1

array([[273, 132, 348, 241, 448, 422],
       [237, 126, 483, 164, 422, 274],
       [328, 419, 336, 340, 174, 370],
       [444, 130, 298, 380, 416, 244],
       [418, 186, 207, 243, 428, 333],
       [165, 103, 162, 363, 476, 140],
       [233, 353, 286, 474, 357, 298],
       [412, 295, 129, 329, 138, 272],
       [358, 252, 211, 144, 434, 349]], dtype=int32)

In [40]:
array1_1,array1_2,array1_3=np.split(array1,3,axis=0)

In [41]:
array1_1

array([[273, 132, 348, 241, 448, 422],
       [237, 126, 483, 164, 422, 274],
       [328, 419, 336, 340, 174, 370]], dtype=int32)

In [42]:
array1_2

array([[444, 130, 298, 380, 416, 244],
       [418, 186, 207, 243, 428, 333],
       [165, 103, 162, 363, 476, 140]], dtype=int32)

In [43]:
array1_3

array([[233, 353, 286, 474, 357, 298],
       [412, 295, 129, 329, 138, 272],
       [358, 252, 211, 144, 434, 349]], dtype=int32)

# colunm wise splitting

In [44]:
array1_1,array1_2,array1_3=np.split(array1,3,axis=1)

In [45]:
array1_1

array([[273, 132],
       [237, 126],
       [328, 419],
       [444, 130],
       [418, 186],
       [165, 103],
       [233, 353],
       [412, 295],
       [358, 252]], dtype=int32)

In [46]:
array1_2

array([[348, 241],
       [483, 164],
       [336, 340],
       [298, 380],
       [207, 243],
       [162, 363],
       [286, 474],
       [129, 329],
       [211, 144]], dtype=int32)

In [47]:
array1_3

array([[448, 422],
       [422, 274],
       [174, 370],
       [416, 244],
       [428, 333],
       [476, 140],
       [357, 298],
       [138, 272],
       [434, 349]], dtype=int32)

# For unequal splitting 

In [48]:
array1=np.random.randint(100,500,size=(9,6))
array1

array([[174, 150, 223, 316, 165, 152],
       [273, 284, 155, 398, 200, 357],
       [417, 151, 479, 183, 406, 184],
       [466, 256, 221, 161, 224, 460],
       [278, 467, 457, 322, 215, 451],
       [144, 447, 472, 325, 408, 219],
       [221, 430, 132, 432, 442, 341],
       [109, 255, 281, 424, 128, 469],
       [163, 306, 213, 117, 204, 132]], dtype=int32)

In [49]:
array1_1,array1_2=np.split(array1,[5],axis=1)

In [50]:
array1_1

array([[174, 150, 223, 316, 165],
       [273, 284, 155, 398, 200],
       [417, 151, 479, 183, 406],
       [466, 256, 221, 161, 224],
       [278, 467, 457, 322, 215],
       [144, 447, 472, 325, 408],
       [221, 430, 132, 432, 442],
       [109, 255, 281, 424, 128],
       [163, 306, 213, 117, 204]], dtype=int32)

In [51]:
array1_2

array([[152],
       [357],
       [184],
       [460],
       [451],
       [219],
       [341],
       [469],
       [132]], dtype=int32)

In [52]:
array1

array([[174, 150, 223, 316, 165, 152],
       [273, 284, 155, 398, 200, 357],
       [417, 151, 479, 183, 406, 184],
       [466, 256, 221, 161, 224, 460],
       [278, 467, 457, 322, 215, 451],
       [144, 447, 472, 325, 408, 219],
       [221, 430, 132, 432, 442, 341],
       [109, 255, 281, 424, 128, 469],
       [163, 306, 213, 117, 204, 132]], dtype=int32)

In [53]:
array1_1,array1_2,array1_3=np.split(array1,[3,5],axis=1)

In [54]:
array1_1

array([[174, 150, 223],
       [273, 284, 155],
       [417, 151, 479],
       [466, 256, 221],
       [278, 467, 457],
       [144, 447, 472],
       [221, 430, 132],
       [109, 255, 281],
       [163, 306, 213]], dtype=int32)

In [55]:
array1_2

array([[316, 165],
       [398, 200],
       [183, 406],
       [161, 224],
       [322, 215],
       [325, 408],
       [432, 442],
       [424, 128],
       [117, 204]], dtype=int32)

In [56]:
array1_3

array([[152],
       [357],
       [184],
       [460],
       [451],
       [219],
       [341],
       [469],
       [132]], dtype=int32)

# Load the dataset into numpy array

In [57]:
iris_array=np.genfromtxt(r"C:\Users\lenovo\OneDrive\Desktop\numpy\Numpy_learning\iris.txt",delimiter=',',dtype=str)

In [58]:
iris_array

array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['5.0', '3.6', '1.4', '0.2', 'Iris-setosa'],
       ['5.4', '3.9', '1.7', '0.4', 'Iris-setosa'],
       ['4.6', '3.4', '1.4', '0.3', 'Iris-setosa'],
       ['5.0', '3.4', '1.5', '0.2', 'Iris-setosa'],
       ['4.4', '2.9', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
       ['5.4', '3.7', '1.5', '0.2', 'Iris-setosa'],
       ['4.8', '3.4', '1.6', '0.2', 'Iris-setosa'],
       ['4.8', '3.0', '1.4', '0.1', 'Iris-setosa'],
       ['4.3', '3.0', '1.1', '0.1', 'Iris-setosa'],
       ['5.8', '4.0', '1.2', '0.2', 'Iris-setosa'],
       ['5.7', '4.4', '1.5', '0.4', 'Iris-setosa'],
       ['5.4', '3.9', '1.3', '0.4', 'Iris-setosa'],
       ['5.1', '3.5', '1.4', '0.3', 'Iris-setosa'],
       ['5.7', '3.8', '1.7', '0.3', 'Iris-setosa'],
       ['5.1

In [59]:
iris_features,iris_species=np.split(iris_array,[4],axis=1)

In [60]:
iris_features

array([['5.1', '3.5', '1.4', '0.2'],
       ['4.9', '3.0', '1.4', '0.2'],
       ['4.7', '3.2', '1.3', '0.2'],
       ['4.6', '3.1', '1.5', '0.2'],
       ['5.0', '3.6', '1.4', '0.2'],
       ['5.4', '3.9', '1.7', '0.4'],
       ['4.6', '3.4', '1.4', '0.3'],
       ['5.0', '3.4', '1.5', '0.2'],
       ['4.4', '2.9', '1.4', '0.2'],
       ['4.9', '3.1', '1.5', '0.1'],
       ['5.4', '3.7', '1.5', '0.2'],
       ['4.8', '3.4', '1.6', '0.2'],
       ['4.8', '3.0', '1.4', '0.1'],
       ['4.3', '3.0', '1.1', '0.1'],
       ['5.8', '4.0', '1.2', '0.2'],
       ['5.7', '4.4', '1.5', '0.4'],
       ['5.4', '3.9', '1.3', '0.4'],
       ['5.1', '3.5', '1.4', '0.3'],
       ['5.7', '3.8', '1.7', '0.3'],
       ['5.1', '3.8', '1.5', '0.3'],
       ['5.4', '3.4', '1.7', '0.2'],
       ['5.1', '3.7', '1.5', '0.4'],
       ['4.6', '3.6', '1.0', '0.2'],
       ['5.1', '3.3', '1.7', '0.5'],
       ['4.8', '3.4', '1.9', '0.2'],
       ['5.0', '3.0', '1.6', '0.2'],
       ['5.0', '3.4', '1.6', '0.4'],
 

In [61]:
iris_species

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-se

In [62]:
iris_features=iris_features.astype(float)

In [63]:
iris_features

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [64]:
iris_features.dtype

dtype('float64')

# Mean Median and Mode

# Mean

In [65]:
array1=np.array([12,14,16,13,10])
mean=np.mean(array1)
mean

np.float64(13.0)

In [66]:
median=np.median(array1)
median

np.float64(13.0)

In [67]:
standard_deviation=np.std(array1)
standard_deviation

np.float64(2.0)

In [68]:
array2=np.array([[1,2,3],[4,5,6],[7,8,9]])
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
array2=np.random.randint(15,25,size=(6,4))
array2

array([[15, 15, 22, 21],
       [19, 17, 22, 22],
       [22, 22, 24, 17],
       [15, 19, 16, 15],
       [22, 18, 18, 24],
       [15, 20, 24, 20]], dtype=int32)

In [70]:
mean2=np.mean(array2,axis=0)

In [71]:
mean2

array([18.        , 18.5       , 21.        , 19.83333333])

In [72]:
iris_features_mean=np.mean(iris_features,axis=0)
iris_features_mean

array([5.84333333, 3.054     , 3.75866667, 1.19866667])