In [129]:
import numpy as np

# Concatenation in numpy array

In [130]:
array1=np.array([[1,2,3],[4,5,6],[7,8,9]])
array1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [131]:
array1=np.array([1,2,3,4])
array2=np.array([5,6,7,8])
array3=np.concatenate((array1,array2))
array3

array([1, 2, 3, 4, 5, 6, 7, 8])

# 2D array concatenation

In [132]:
array1=np.array([[1,2,3,4],
                 [4,5,6,7],
                 [7,8,9,7]])
array2=np.array([[8,2,5,7],
                 [4,7,0,7],
                 [7,9,8,7]])

In [133]:
np.concatenate((array1,array2),axis=0)

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [7, 8, 9, 7],
       [8, 2, 5, 7],
       [4, 7, 0, 7],
       [7, 9, 8, 7]])

In [134]:
np.concatenate((array1,array2),axis=1)

array([[1, 2, 3, 4, 8, 2, 5, 7],
       [4, 5, 6, 7, 4, 7, 0, 7],
       [7, 8, 9, 7, 7, 9, 8, 7]])

# hstack and vstack

In [135]:
array1=np.array([[1,2,3,4],
                 [4,5,6,7]])
array2=np.array([[8,2,5,7]])

In [136]:
np.vstack((array1,array2))

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [8, 2, 5, 7]])

In [137]:
array3=np.array([[23],
                 [34]])


In [138]:
np.hstack((array1,array3))

array([[ 1,  2,  3,  4, 23],
       [ 4,  5,  6,  7, 34]])

# Slicing in numpy array 

In [139]:
array1=np.arange(1,11)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [140]:
array=array1[3:7]
array

array([4, 5, 6, 7])

# For 2D array slicing 

In [141]:
array2=np.array([[4,5,6,7],
                 [12,23,45,67],
                 [12,32,45,66]])
array2.shape

(3, 4)

In [142]:
print(array2[1,1])

23


In [143]:
print(array2[1,3])

67


In [144]:
print(array2[2,2])

45


In [145]:
array2[1:3,1:3]

array([[23, 45],
       [32, 45]])

In [146]:
array2[0:,1:3]

array([[ 5,  6],
       [23, 45],
       [32, 45]])

# Reshaping method in numpy array 

In [147]:
array2

array([[ 4,  5,  6,  7],
       [12, 23, 45, 67],
       [12, 32, 45, 66]])

In [148]:
array2.shape

(3, 4)

In [149]:
array2.reshape(4,3)

array([[ 4,  5,  6],
       [ 7, 12, 23],
       [45, 67, 12],
       [32, 45, 66]])

In [150]:
array2.reshape(2,6)

array([[ 4,  5,  6,  7, 12, 23],
       [45, 67, 12, 32, 45, 66]])

In [151]:
array2.reshape(6,2)

array([[ 4,  5],
       [ 6,  7],
       [12, 23],
       [45, 67],
       [12, 32],
       [45, 66]])

In [152]:
array2.reshape(12)

array([ 4,  5,  6,  7, 12, 23, 45, 67, 12, 32, 45, 66])

In [153]:
array2.reshape(2,3,2)

array([[[ 4,  5],
        [ 6,  7],
        [12, 23]],

       [[45, 67],
        [12, 32],
        [45, 66]]])

In [154]:
array=np.arange(1,101)
array

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [155]:
array.reshape(20,5)

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

# Day 4

# Random array in numpy

In [156]:
# rand() gives the random value betwen 0-1
# randint() gives the random integer value in given range

In [157]:
array_1= np.random.rand(4, 6)
array_1

array([[0.30738078, 0.4560543 , 0.0481957 , 0.59865186, 0.84298468,
        0.07916356],
       [0.77256307, 0.64762409, 0.4399911 , 0.22310569, 0.46354593,
        0.29548456],
       [0.51633213, 0.53239223, 0.39658091, 0.34494664, 0.51428174,
        0.56970834],
       [0.34181472, 0.05160054, 0.14001811, 0.24819665, 0.88321397,
        0.12867864]])

In [158]:
array_2= np.random.rand(10)
array_2

array([0.25940838, 0.35702633, 0.42750415, 0.95696819, 0.38482682,
       0.83871151, 0.05170853, 0.33565395, 0.50461805, 0.78740387])

# Randint method

In [159]:
array3= np.random.randint(1,100,size=10)
array3

array([78, 34, 14,  3, 83, 42, 25, 75, 24, 26], dtype=int32)

# splitting in numpy array 

In [160]:
array1=np.random.randint(100,500,size=(10,6))
array1

array([[372, 431, 127, 149, 380, 483],
       [410, 349, 241, 154, 322, 206],
       [428, 117, 285, 358, 449, 308],
       [294, 309, 403, 106, 114, 260],
       [149, 359, 473, 293, 114, 313],
       [284, 217, 160, 115, 287, 281],
       [476, 360, 458, 473, 211, 267],
       [279, 437, 384, 464, 294, 196],
       [348, 152, 379, 404, 469, 370],
       [204, 409, 158, 345, 366, 472]], dtype=int32)

In [161]:
array1_1,array1_2=np.split(array1,2,axis=0)

In [162]:
array1_1

array([[372, 431, 127, 149, 380, 483],
       [410, 349, 241, 154, 322, 206],
       [428, 117, 285, 358, 449, 308],
       [294, 309, 403, 106, 114, 260],
       [149, 359, 473, 293, 114, 313]], dtype=int32)

In [163]:
array1_2

array([[284, 217, 160, 115, 287, 281],
       [476, 360, 458, 473, 211, 267],
       [279, 437, 384, 464, 294, 196],
       [348, 152, 379, 404, 469, 370],
       [204, 409, 158, 345, 366, 472]], dtype=int32)

In [164]:
array1_1,array1_2=np.split(array1,2,axis=1)

In [165]:
array1_1

array([[372, 431, 127],
       [410, 349, 241],
       [428, 117, 285],
       [294, 309, 403],
       [149, 359, 473],
       [284, 217, 160],
       [476, 360, 458],
       [279, 437, 384],
       [348, 152, 379],
       [204, 409, 158]], dtype=int32)

In [166]:
array1_2

array([[149, 380, 483],
       [154, 322, 206],
       [358, 449, 308],
       [106, 114, 260],
       [293, 114, 313],
       [115, 287, 281],
       [473, 211, 267],
       [464, 294, 196],
       [404, 469, 370],
       [345, 366, 472]], dtype=int32)

In [167]:
array1=np.random.randint(100,500,size=(9,6))
array1

array([[345, 379, 166, 239, 397, 461],
       [200, 198, 279, 189, 230, 394],
       [490, 193, 368, 366, 207, 144],
       [256, 346, 362, 424, 390, 462],
       [294, 350, 354, 341, 376, 452],
       [498, 452, 118, 395, 160, 218],
       [394, 446, 255, 261, 143, 403],
       [375, 386, 373, 336, 233, 374],
       [179, 289, 238, 325, 137, 402]], dtype=int32)

In [168]:
array1_1,array1_2,array1_3=np.split(array1,3,axis=0)

In [169]:
array1_1

array([[345, 379, 166, 239, 397, 461],
       [200, 198, 279, 189, 230, 394],
       [490, 193, 368, 366, 207, 144]], dtype=int32)

In [170]:
array1_2

array([[256, 346, 362, 424, 390, 462],
       [294, 350, 354, 341, 376, 452],
       [498, 452, 118, 395, 160, 218]], dtype=int32)

In [171]:
array1_3

array([[394, 446, 255, 261, 143, 403],
       [375, 386, 373, 336, 233, 374],
       [179, 289, 238, 325, 137, 402]], dtype=int32)

# colunm wise splitting

In [172]:
array1_1,array1_2,array1_3=np.split(array1,3,axis=1)

In [173]:
array1_1

array([[345, 379],
       [200, 198],
       [490, 193],
       [256, 346],
       [294, 350],
       [498, 452],
       [394, 446],
       [375, 386],
       [179, 289]], dtype=int32)

In [174]:
array1_2

array([[166, 239],
       [279, 189],
       [368, 366],
       [362, 424],
       [354, 341],
       [118, 395],
       [255, 261],
       [373, 336],
       [238, 325]], dtype=int32)

In [175]:
array1_3

array([[397, 461],
       [230, 394],
       [207, 144],
       [390, 462],
       [376, 452],
       [160, 218],
       [143, 403],
       [233, 374],
       [137, 402]], dtype=int32)

# For unequal splitting 

In [176]:
array1=np.random.randint(100,500,size=(9,6))
array1

array([[104, 300, 160, 175, 310, 406],
       [358, 432, 170, 111, 219, 431],
       [459, 141, 332, 382, 176, 220],
       [415, 433, 264, 247, 280, 295],
       [249, 191, 352, 119, 343, 428],
       [401, 351, 236, 279, 367, 483],
       [161, 242, 137, 188, 184, 355],
       [404, 465, 123, 307, 452, 464],
       [412, 316, 342, 409, 414, 483]], dtype=int32)

In [177]:
array1_1,array1_2=np.split(array1,[5],axis=1)

In [178]:
array1_1

array([[104, 300, 160, 175, 310],
       [358, 432, 170, 111, 219],
       [459, 141, 332, 382, 176],
       [415, 433, 264, 247, 280],
       [249, 191, 352, 119, 343],
       [401, 351, 236, 279, 367],
       [161, 242, 137, 188, 184],
       [404, 465, 123, 307, 452],
       [412, 316, 342, 409, 414]], dtype=int32)

In [179]:
array1_2

array([[406],
       [431],
       [220],
       [295],
       [428],
       [483],
       [355],
       [464],
       [483]], dtype=int32)

In [180]:
array1

array([[104, 300, 160, 175, 310, 406],
       [358, 432, 170, 111, 219, 431],
       [459, 141, 332, 382, 176, 220],
       [415, 433, 264, 247, 280, 295],
       [249, 191, 352, 119, 343, 428],
       [401, 351, 236, 279, 367, 483],
       [161, 242, 137, 188, 184, 355],
       [404, 465, 123, 307, 452, 464],
       [412, 316, 342, 409, 414, 483]], dtype=int32)

In [181]:
array1_1,array1_2,array1_3=np.split(array1,[3,5],axis=1)

In [182]:
array1_1

array([[104, 300, 160],
       [358, 432, 170],
       [459, 141, 332],
       [415, 433, 264],
       [249, 191, 352],
       [401, 351, 236],
       [161, 242, 137],
       [404, 465, 123],
       [412, 316, 342]], dtype=int32)

In [183]:
array1_2

array([[175, 310],
       [111, 219],
       [382, 176],
       [247, 280],
       [119, 343],
       [279, 367],
       [188, 184],
       [307, 452],
       [409, 414]], dtype=int32)

In [184]:
array1_3

array([[406],
       [431],
       [220],
       [295],
       [428],
       [483],
       [355],
       [464],
       [483]], dtype=int32)

# Load the dataset into numpy array

In [185]:
iris_array=np.genfromtxt(r"C:\Users\lenovo\OneDrive\Desktop\numpy\Numpy_learning\iris.txt",delimiter=',',dtype=str)

In [186]:
iris_array

array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['5.0', '3.6', '1.4', '0.2', 'Iris-setosa'],
       ['5.4', '3.9', '1.7', '0.4', 'Iris-setosa'],
       ['4.6', '3.4', '1.4', '0.3', 'Iris-setosa'],
       ['5.0', '3.4', '1.5', '0.2', 'Iris-setosa'],
       ['4.4', '2.9', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
       ['5.4', '3.7', '1.5', '0.2', 'Iris-setosa'],
       ['4.8', '3.4', '1.6', '0.2', 'Iris-setosa'],
       ['4.8', '3.0', '1.4', '0.1', 'Iris-setosa'],
       ['4.3', '3.0', '1.1', '0.1', 'Iris-setosa'],
       ['5.8', '4.0', '1.2', '0.2', 'Iris-setosa'],
       ['5.7', '4.4', '1.5', '0.4', 'Iris-setosa'],
       ['5.4', '3.9', '1.3', '0.4', 'Iris-setosa'],
       ['5.1', '3.5', '1.4', '0.3', 'Iris-setosa'],
       ['5.7', '3.8', '1.7', '0.3', 'Iris-setosa'],
       ['5.1

In [187]:
iris_features,iris_species=np.split(iris_array,[4],axis=1)

In [188]:
iris_features

array([['5.1', '3.5', '1.4', '0.2'],
       ['4.9', '3.0', '1.4', '0.2'],
       ['4.7', '3.2', '1.3', '0.2'],
       ['4.6', '3.1', '1.5', '0.2'],
       ['5.0', '3.6', '1.4', '0.2'],
       ['5.4', '3.9', '1.7', '0.4'],
       ['4.6', '3.4', '1.4', '0.3'],
       ['5.0', '3.4', '1.5', '0.2'],
       ['4.4', '2.9', '1.4', '0.2'],
       ['4.9', '3.1', '1.5', '0.1'],
       ['5.4', '3.7', '1.5', '0.2'],
       ['4.8', '3.4', '1.6', '0.2'],
       ['4.8', '3.0', '1.4', '0.1'],
       ['4.3', '3.0', '1.1', '0.1'],
       ['5.8', '4.0', '1.2', '0.2'],
       ['5.7', '4.4', '1.5', '0.4'],
       ['5.4', '3.9', '1.3', '0.4'],
       ['5.1', '3.5', '1.4', '0.3'],
       ['5.7', '3.8', '1.7', '0.3'],
       ['5.1', '3.8', '1.5', '0.3'],
       ['5.4', '3.4', '1.7', '0.2'],
       ['5.1', '3.7', '1.5', '0.4'],
       ['4.6', '3.6', '1.0', '0.2'],
       ['5.1', '3.3', '1.7', '0.5'],
       ['4.8', '3.4', '1.9', '0.2'],
       ['5.0', '3.0', '1.6', '0.2'],
       ['5.0', '3.4', '1.6', '0.4'],
 

In [189]:
iris_species

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-se

In [190]:
iris_features=iris_features.astype(float)

In [191]:
iris_features

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [192]:
iris_features.dtype

dtype('float64')

# Mean Median and Mode

# Mean

In [193]:
array1=np.array([12,14,16,13,10])
mean=np.mean(array1)
mean

np.float64(13.0)

In [194]:
median=np.median(array1)
median

np.float64(13.0)

In [195]:
standard_deviation=np.std(array1)
standard_deviation

np.float64(2.0)

In [196]:
array2=np.array([[1,2,3],[4,5,6],[7,8,9]])
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [197]:
array2=np.random.randint(15,25,size=(6,4))
array2

array([[18, 21, 22, 23],
       [22, 15, 22, 22],
       [22, 23, 21, 21],
       [18, 15, 22, 17],
       [21, 24, 20, 18],
       [24, 23, 18, 16]], dtype=int32)

In [198]:
mean2=np.mean(array2,axis=0)

In [199]:
mean2

array([20.83333333, 20.16666667, 20.83333333, 19.5       ])

In [200]:
iris_features_mean=np.mean(iris_features,axis=0)
iris_features_mean

array([5.84333333, 3.054     , 3.75866667, 1.19866667])