In [26]:
import numpy as np

### A 1-D array called zeros having 10 elements and all the elements are set to zero.  

In [27]:
zeros=np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

###  A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’.

In [28]:
vowels=np.array(['a','e','i','o','u'])
vowels

array(['a', 'e', 'i', 'o', 'u'], dtype='<U1')

###  A 2-D array called ones having 2 rows and 5 columns and all the elements are set to 1 and dtype as int.  

In [29]:
ones=np.ones((2,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

###  Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data:  

In [30]:
myarray1=np.array([[2.7, -2, -19 ],
           [0, 3.4, 99.9 ],
           [10.6, 0, 13]])
myarray1

array([[  2.7,  -2. , -19. ],
       [  0. ,   3.4,  99.9],
       [ 10.6,   0. ,  13. ]])

###  A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float. 

In [31]:
myarray2=np.arange(4,4+15*4,4,dtype=float).reshape(3,5)
myarray2

array([[ 4.,  8., 12., 16., 20.],
       [24., 28., 32., 36., 40.],
       [44., 48., 52., 56., 60.]])

# Question no 2

####  Find the dimensions, shape, size, data type of the items and itemsize of arrays zeros, vowels, ones, myarray1 and myarray2. 

In [32]:
np.ndim(myarray2)

2

In [33]:
np.shape(myarray2)

(3, 5)

In [34]:
np.size(myarray2)

15

In [35]:
myarray2.dtype

dtype('float64')

In [36]:
zeros.shape

(10,)

In [37]:
zeros.size

10

In [38]:
zeros.dtype

dtype('float64')

In [39]:
vowels.dtype

dtype('<U1')

In [40]:
vowels.astype(str)

array(['a', 'e', 'i', 'o', 'u'], dtype='<U1')

In [41]:
vowels.shape

(5,)

In [42]:
vowels.size

5

####  Reshape the array ones to have all the 10 elements in a single column.

In [43]:
zeros.reshape(10,1)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

####  Display the 2nd and 3rd element of the array vowels.  

In [44]:
print(vowels[1:3])

['e' 'i']


####  Display all elements in the 2nd and 3rd row of the array myarray1. 

In [45]:
myarray1_1,myarray1_2=np.split(myarray1,[1],axis=0)

In [46]:
myarray1_2

array([[ 0. ,  3.4, 99.9],
       [10.6,  0. , 13. ]])

#### Display the elements in the 1st and 2nd column of the array myarray1.  

In [47]:
myarray1_1,myarray1_2=np.split(myarray1,[2],axis=1)

In [48]:
myarray1_1

array([[ 2.7, -2. ],
       [ 0. ,  3.4],
       [10.6,  0. ]])

In [49]:
myarray1

array([[  2.7,  -2. , -19. ],
       [  0. ,   3.4,  99.9],
       [ 10.6,   0. ,  13. ]])

#### Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1.  

In [52]:
myarray1[1:3, 0]

array([ 0. , 10.6])

#### Reverse the array of vowels.  

In [ ]:
vowels[-1:]

array([], dtype='<U1')